#!/bin/bash
#BSUB -P acc_oscarlr
#BSUB -J inspect_overlaps
#BSUB -W 0:10
#BSUB -M 4000
#BSUB -n 1
#BSUB -o overlap.out
#BSUB -e overlap_vThree.err

module load python/3.12.5
python find_1kg_overlap.py
